### ISSUE TITLE
Needs better documentation and Usage instructions/Examples

### ISSUE THREAD

**Issue by TheAnarchoX** [40818419/vue-router-sitemap#10]
the README.md is very minimal and very unclear. The example given uses variables that are not specifically defined in itself, like the ```app``` variable, it is not imported nor is any specifaction given on the context of this variable

**Comment by lewiswilbynm** [comment]
> the README.md is very minimal and very unclear. The example given uses variables that are not specifically defined in itself, like the `app` variable, it is not imported nor is any specifaction given on the context of this variable

Did anyone figure out what app is related too? Also I can only assume we replace "http://example.com" with our URL?

**Comment by fend25** [comment]
app is web server instance (i.e. express)

**Comment by fdenzer** [comment]
https://zigamiklic.com/simple-sitemap-for-vue-router/ looks useful, but uses a function (either `getRoutesList` or `getRoutesXML`) instead of the middleware approach

**Comment by tettoffensive** [comment]
Anyone ever figure out how to use this? I recognized that app.get might be something express related. But I think most of us don't have a web server instance in our Vue application

**Comment by bartoszwalacik** [comment]
I also don't know what is `app.get()` and how to plug `sitemapMiddleware()` into `Vue`. Looks like the author wont tell us how to use this lib.

**Comment by yangwao** [comment]
Make fork 💃

**Comment by HydenLiu** [comment]
笑死，大家都不知道app是哪来的，giao，这玩意儿到底在哪用
