### ISSUE TITLE
npm i --save vue-router-sitemap npm ERR! E404

### ISSUE THREAD

**Issue by SamHz** [40818419/vue-router-sitemap#7]
npm install has version number?  it's not work
`npm ERR! code E404`
`npm ERR! 404 Not Found: vue-router-sitemap@latest`

**Comment by 40818419** [comment]
it wasn't published yet...

**Comment by SamHz** [comment]
@40818419 wooooo... I came too early.If it working good, it can help me reduce the possibility of refactoring. :) thank you

**Comment by 40818419** [comment]
@SamHz that's my intention :) will need to get done, those issues i created, before publishing
